version: "3.8"

services:
  foodai-backend:
    # image: 888722447205.dkr.ecr.us-east-1.amazonaws.com/foodai:latest
    build: .
    container_name: foodai-backend
    restart: always
    command: ["sh", "-c", "python manage.py migrate --noinput && gunicorn --bind 0.0.0.0:8018 foodanalysis.wsgi:application"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    networks:
      - foodai_network
    depends_on:
      - foodai-db

  foodai-db:
    image: postgres:15
    container_name: foodai-db
    restart: always
    environment:
      POSTGRES_DB: foodai
      POSTGRES_USER: foodai_user
      POSTGRES_PASSWORD: pass098foodai1123
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - foodai_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  foodai-nginx:
    # image: 888722447205.dkr.ecr.us-east-1.amazonaws.com/foodai-nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: foodai-nginx
    restart: always
    ports:
      # - "80:80"
      # - "443:443"
      - "8018:80"
    networks:
      - foodai_network
    depends_on:
      - foodai-backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro

networks:
  foodai_network:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/abhishek/Desktop/Foodapp/foodapp_backend/dbdata